Merge from wip

diff --git a/cgi/factory b/cgi/factory
--- a/cgi/factory
+++ b/cgi/factory
@@ -1,8 +1,7 @@
 #!/bin/bash
-# return factory server IP and cgi port
-source ${0%/*}/cgi.inc
-
-lookup() { awk 'BEGIN{X=1} {gsub(/[ \t]+/,"");if($1=="'$1'"){print $2; X=0; exit}} END{exit X}' FS== $base/pionic.cfg; }
-factory=$(lookup factory_ip)
-[[ $factory ]] || die "factory_ip not configured"
-echo $factory
+# return factory server IP from parameter cache
+here=${0%/*}
+source $here/cgi.inc
+set -- $(cat /tmp/pionic/.cached 2>/dev/null)
+(($#)) || die "Cached parameters missing or invalid"
+echo $1
